[package]
name = "ciclo_de_vida"
version = "0.1.0"
authors = ["abraham"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
