[package]
name = "demo"
version = "0.1.0"
authors = ["abrahamx9-r <abraham_g_r@ciencias.unam.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
